language: java
sudo: false
jdk:
  - openjdk11
branches:
  except:
    - travis
notifications:
  irc:
    channels:
      - "chat.freenode.net#craftercms"
    use_notice: true
    skip_join: true
  slack: craftersoftware:7YiSb41ZG5rfMgiAY7Qgprc7
env:
  global:
    - secure: YZzNy4zK2Yj+YyooEAVc/I1EA36UUS6oYS1eLG6CyY4fbhwklAvrgTUBZva2jpmafnoW2KFoxwINKqvMGBLGoI/4PxtYwMk+PsxXt7Xt1Rb4FdntMV+H7vqIrKbkFZSvkicB0y6mWDc8BPUtMkigPT/syLgAkR8FzYu658czDUc=
    - secure: PWioVvBVkbi/9JkGDem5/0dMo/gyzfi1/BNgoUKOKgMZxP2hy1AdBQEuK763eN59Zqj/m41Lwjxz1AqsCdgIOMYMUR+aHsisfMRko1Fh4mbgdtGMIHcvnf18HbsnYwXdIbInrcgOZPKZWTW8iQAYiwzemSlD61xNcYnwL6Qdo2U=
script:
  - 'if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then bash -c  "mvn deploy --settings .travis-settings.xml";  fi'
  - 'if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then bash -c "mvn clean install" ;fi'
