language: java
sudo: false
jdk:
- openjdk11
branches:
  only:
  - develop
  - support/.*
  - master
cache:
  directories:
    - $HOME/.m2
notifications:
  irc:
    channels:
    - chat.freenode.net#craftercms
    use_notice: true
    skip_join: true
  slack: craftersoftware:7YiSb41ZG5rfMgiAY7Qgprc7
script:
- if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then bash -c  "mvn deploy --settings
  .travis-settings.xml";  fi
- if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then bash -c "mvn clean install" ;fi
env:
  global:
  - secure: R1Q8FLbWMc94uiUTmgK3OIl6NyuoTANkyovXKaso5++Odw5/ULY6xQeLFg9dDYcbmK0aiNtCYc+Y39kQwkEtXyZn3hx7T2OkOFZ6f8+vGjepSOhoBNU51D8E/zrEp6U2TP1pgykMTRJOaoVFS5vO/im5ttLPRJ2RtAaaXMZmOXQ=
  - secure: RWC7VJc33eB3i+UQeDohYtF3TXMgZtihc1Y6UVhr8IHZBi7rGrkXFNhqx4VMvPeDaScO4bjm84D3XIJsp2O3xtbemnYIgveJD34cL+70OJe0IFCIAGcYyg3QQehZAkFLOjQ1ei22fXWIUNwMAre+N7wqZ1tU0VyPhJxBmke+wlw=
